export const exampleSoupSchematic = [
  {
    type: "source_component",
    source_component_id: "simple_resistor_0",
    name: "R1",
    ftype: "simple_resistor",
    resistance: "10 ohm",
    source: {
      type: "source_component",
      source_component_id: "simple_resistor_0",
      name: "R1",
      ftype: "simple_resistor",
      resistance: "10 ohm",
    },
  },
  {
    type: "schematic_component",
    source_component_id: "simple_resistor_0",
    schematic_component_id: "schematic_component_simple_resistor_0",
    rotation: 0,
    size: {
      width: 1,
      height: 0.3,
    },
    center: {
      x: 2,
      y: 1,
    },
    source: {
      type: "source_component",
      source_component_id: "simple_resistor_0",
      name: "R1",
      ftype: "simple_resistor",
      resistance: "10 ohm",
    },
  },
  {
    type: "source_port",
    name: "left",
    source_port_id: "source_port_0",
    source_component_id: "simple_resistor_0",
    source: {
      type: "source_component",
      source_component_id: "simple_resistor_0",
      name: "R1",
      ftype: "simple_resistor",
      resistance: "10 ohm",
    },
  },
  {
    type: "schematic_port",
    schematic_port_id: "schematic_port_0",
    source_port_id: "source_port_0",
    center: {
      x: 1.5,
      y: 1,
    },
    facing_direction: "left",
    schematic_component_id: "schematic_component_simple_resistor_0",
    source: {
      type: "source_port",
      name: "left",
      source_port_id: "source_port_0",
      source_component_id: "simple_resistor_0",
    },
  },
  {
    type: "source_port",
    name: "right",
    source_port_id: "source_port_1",
    source_component_id: "simple_resistor_0",
    source: {
      type: "source_component",
      source_component_id: "simple_resistor_0",
      name: "R1",
      ftype: "simple_resistor",
      resistance: "10 ohm",
    },
  },
  {
    type: "schematic_port",
    schematic_port_id: "schematic_port_1",
    source_port_id: "source_port_1",
    center: {
      x: 2.5,
      y: 1,
    },
    facing_direction: "right",
    schematic_component_id: "schematic_component_simple_resistor_0",
    source: {
      type: "source_port",
      name: "right",
      source_port_id: "source_port_1",
      source_component_id: "simple_resistor_0",
    },
  },
  {
    type: "schematic_text",
    text: "R1",
    schematic_text_id: "schematic_text_0",
    schematic_component_id: "schematic_component_simple_resistor_0",
    anchor: "left",
    position: {
      x: 1.8,
      y: 0.5,
    },
    source: null,
  },
  {
    type: "schematic_text",
    text: "10 ohm",
    schematic_text_id: "schematic_text_1",
    schematic_component_id: "schematic_component_simple_resistor_0",
    anchor: "left",
    position: {
      x: 1.8,
      y: 0.7,
    },
    source: null,
  },
  {
    type: "source_component",
    source_component_id: "simple_capacitor_0",
    name: "C1",
    ftype: "simple_capacitor",
    capacitance: "10 uF",
    source: {
      type: "source_component",
      source_component_id: "simple_capacitor_0",
      name: "C1",
      ftype: "simple_capacitor",
      capacitance: "10 uF",
    },
  },
  {
    type: "schematic_component",
    source_component_id: "simple_capacitor_0",
    schematic_component_id: "schematic_component_simple_capacitor_0",
    rotation: 1.5707963267948966,
    size: {
      width: 0.75,
      height: 0.75,
    },
    center: {
      x: 4,
      y: 2,
    },
    source: {
      type: "source_component",
      source_component_id: "simple_capacitor_0",
      name: "C1",
      ftype: "simple_capacitor",
      capacitance: "10 uF",
    },
  },
  {
    type: "source_port",
    name: "left",
    source_port_id: "source_port_2",
    source_component_id: "simple_capacitor_0",
    source: {
      type: "source_component",
      source_component_id: "simple_capacitor_0",
      name: "C1",
      ftype: "simple_capacitor",
      capacitance: "10 uF",
    },
  },
  {
    type: "schematic_port",
    schematic_port_id: "schematic_port_2",
    source_port_id: "source_port_2",
    center: {
      x: 4,
      y: 1.5,
    },
    facing_direction: "up",
    schematic_component_id: "schematic_component_simple_capacitor_0",
    source: {
      type: "source_port",
      name: "left",
      source_port_id: "source_port_2",
      source_component_id: "simple_capacitor_0",
    },
  },
  {
    type: "source_port",
    name: "right",
    source_port_id: "source_port_3",
    source_component_id: "simple_capacitor_0",
    source: {
      type: "source_component",
      source_component_id: "simple_capacitor_0",
      name: "C1",
      ftype: "simple_capacitor",
      capacitance: "10 uF",
    },
  },
  {
    type: "schematic_port",
    schematic_port_id: "schematic_port_3",
    source_port_id: "source_port_3",
    center: {
      x: 4,
      y: 2.5,
    },
    facing_direction: "down",
    schematic_component_id: "schematic_component_simple_capacitor_0",
    source: {
      type: "source_port",
      name: "right",
      source_port_id: "source_port_3",
      source_component_id: "simple_capacitor_0",
    },
  },
  {
    type: "schematic_text",
    text: "C1",
    schematic_text_id: "schematic_text_2",
    schematic_component_id: "schematic_component_simple_capacitor_0",
    anchor: "left",
    position: {
      x: 4.3,
      y: 1.5,
    },
    source: null,
  },
  {
    type: "schematic_text",
    text: "10 uF",
    schematic_text_id: "schematic_text_3",
    schematic_component_id: "schematic_component_simple_capacitor_0",
    anchor: "left",
    position: {
      x: 4.3,
      y: 1.7,
    },
    source: null,
  },
  {
    type: "source_component",
    source_component_id: "simple_resistor_1",
    name: "R2",
    ftype: "simple_resistor",
    resistance: "10 ohm",
    source: {
      type: "source_component",
      source_component_id: "simple_resistor_1",
      name: "R2",
      ftype: "simple_resistor",
      resistance: "10 ohm",
    },
  },
  {
    type: "schematic_component",
    source_component_id: "simple_resistor_1",
    schematic_component_id: "schematic_component_simple_resistor_1",
    rotation: 1.5707963267948966,
    size: {
      width: 1,
      height: 0.3,
    },
    center: {
      x: 6,
      y: 1,
    },
    source: {
      type: "source_component",
      source_component_id: "simple_resistor_1",
      name: "R2",
      ftype: "simple_resistor",
      resistance: "10 ohm",
    },
  },
  {
    type: "source_port",
    name: "left",
    source_port_id: "source_port_4",
    source_component_id: "simple_resistor_1",
    source: {
      type: "source_component",
      source_component_id: "simple_resistor_1",
      name: "R2",
      ftype: "simple_resistor",
      resistance: "10 ohm",
    },
  },
  {
    type: "schematic_port",
    schematic_port_id: "schematic_port_4",
    source_port_id: "source_port_4",
    center: {
      x: 6,
      y: 0.5,
    },
    facing_direction: "up",
    schematic_component_id: "schematic_component_simple_resistor_1",
    source: {
      type: "source_port",
      name: "left",
      source_port_id: "source_port_4",
      source_component_id: "simple_resistor_1",
    },
  },
  {
    type: "source_port",
    name: "right",
    source_port_id: "source_port_5",
    source_component_id: "simple_resistor_1",
    source: {
      type: "source_component",
      source_component_id: "simple_resistor_1",
      name: "R2",
      ftype: "simple_resistor",
      resistance: "10 ohm",
    },
  },
  {
    type: "schematic_port",
    schematic_port_id: "schematic_port_5",
    source_port_id: "source_port_5",
    center: {
      x: 6,
      y: 1.5,
    },
    facing_direction: "down",
    schematic_component_id: "schematic_component_simple_resistor_1",
    source: {
      type: "source_port",
      name: "right",
      source_port_id: "source_port_5",
      source_component_id: "simple_resistor_1",
    },
  },
  {
    type: "schematic_text",
    text: "R2",
    schematic_text_id: "schematic_text_4",
    schematic_component_id: "schematic_component_simple_resistor_1",
    anchor: "left",
    position: {
      x: 6.3,
      y: 0.7999999999999999,
    },
    source: null,
  },
  {
    type: "schematic_text",
    text: "10 ohm",
    schematic_text_id: "schematic_text_5",
    schematic_component_id: "schematic_component_simple_resistor_1",
    anchor: "left",
    position: {
      x: 6.3,
      y: 1,
    },
    source: null,
  },
  {
    type: "source_component",
    source_component_id: "simple_power_source_0",
    name: "main_power",
    ftype: "simple_power_source",
    voltage: "5V",
    source: {
      type: "source_component",
      source_component_id: "simple_power_source_0",
      name: "main_power",
      ftype: "simple_power_source",
      voltage: "5V",
    },
  },
  {
    type: "schematic_component",
    source_component_id: "simple_power_source_0",
    schematic_component_id: "schematic_component_simple_power_source_0",
    rotation: 0,
    size: {
      width: 0.7058823529411765,
      height: 1,
    },
    center: {
      x: 1,
      y: 2,
    },
    source: {
      type: "source_component",
      source_component_id: "simple_power_source_0",
      name: "main_power",
      ftype: "simple_power_source",
      voltage: "5V",
    },
  },
  {
    type: "source_port",
    name: "positive",
    source_port_id: "source_port_6",
    source_component_id: "simple_power_source_0",
    source: {
      type: "source_component",
      source_component_id: "simple_power_source_0",
      name: "main_power",
      ftype: "simple_power_source",
      voltage: "5V",
    },
  },
  {
    type: "schematic_port",
    schematic_port_id: "schematic_port_6",
    source_port_id: "source_port_6",
    center: {
      x: 1,
      y: 1.5,
    },
    facing_direction: "up",
    schematic_component_id: "schematic_component_simple_power_source_0",
    source: {
      type: "source_port",
      name: "positive",
      source_port_id: "source_port_6",
      source_component_id: "simple_power_source_0",
    },
  },
  {
    type: "source_port",
    name: "negative",
    source_port_id: "source_port_7",
    source_component_id: "simple_power_source_0",
    source: {
      type: "source_component",
      source_component_id: "simple_power_source_0",
      name: "main_power",
      ftype: "simple_power_source",
      voltage: "5V",
    },
  },
  {
    type: "schematic_port",
    schematic_port_id: "schematic_port_7",
    source_port_id: "source_port_7",
    center: {
      x: 1,
      y: 2.5,
    },
    facing_direction: "down",
    schematic_component_id: "schematic_component_simple_power_source_0",
    source: {
      type: "source_port",
      name: "negative",
      source_port_id: "source_port_7",
      source_component_id: "simple_power_source_0",
    },
  },
  {
    type: "source_component",
    source_component_id: "simple_bug_0",
    name: "B1",
    ftype: "simple_bug",
    source: {
      type: "source_component",
      source_component_id: "simple_bug_0",
      name: "B1",
      ftype: "simple_bug",
    },
  },
  {
    type: "schematic_component",
    source_component_id: "simple_bug_0",
    schematic_component_id: "schematic_component_simple_bug_0",
    rotation: 0,
    size: {
      width: 1,
      height: 1.5,
    },
    center: {
      x: 8,
      y: 3,
    },
    port_arrangement: {
      left_size: 3,
      right_size: 3,
    },
    port_labels: {
      "1": "PWR",
      "2": "NC",
      "3": "RG",
      "4": "D0",
      "5": "D1",
      "6": "GND",
    },
    source: {
      type: "source_component",
      source_component_id: "simple_bug_0",
      name: "B1",
      ftype: "simple_bug",
    },
  },
  {
    type: "source_port",
    name: "PWR",
    source_port_id: "source_port_8",
    source_component_id: "simple_bug_0",
    pin_number: 1,
    source: {
      type: "source_component",
      source_component_id: "simple_bug_0",
      name: "B1",
      ftype: "simple_bug",
    },
  },
  {
    type: "schematic_port",
    schematic_port_id: "schematic_port_8",
    source_port_id: "source_port_8",
    center: {
      x: 7.25,
      y: 2.5,
    },
    facing_direction: "left",
    schematic_component_id: "schematic_component_simple_bug_0",
    source: {
      type: "source_port",
      name: "PWR",
      source_port_id: "source_port_8",
      source_component_id: "simple_bug_0",
      pin_number: 1,
    },
  },
  {
    type: "schematic_text",
    schematic_port_id: "schematic_port_8",
    schematic_text_id: "schematic_text_12",
    text: "1",
    anchor: "center",
    rotation: 0,
    position: {
      x: 7.373743686707646,
      y: 2.3762563132923544,
    },
    schematic_component_id: "schematic_component_simple_bug_0",
    source: null,
  },
  {
    type: "source_port",
    name: "NC",
    source_port_id: "source_port_9",
    source_component_id: "simple_bug_0",
    pin_number: 2,
    source: {
      type: "source_component",
      source_component_id: "simple_bug_0",
      name: "B1",
      ftype: "simple_bug",
    },
  },
  {
    type: "schematic_port",
    schematic_port_id: "schematic_port_9",
    source_port_id: "source_port_9",
    center: {
      x: 7.25,
      y: 3,
    },
    facing_direction: "left",
    schematic_component_id: "schematic_component_simple_bug_0",
    source: {
      type: "source_port",
      name: "NC",
      source_port_id: "source_port_9",
      source_component_id: "simple_bug_0",
      pin_number: 2,
    },
  },
  {
    type: "schematic_text",
    schematic_port_id: "schematic_port_9",
    schematic_text_id: "schematic_text_13",
    text: "2",
    anchor: "center",
    rotation: 0,
    position: {
      x: 7.373743686707646,
      y: 2.876256313292354,
    },
    schematic_component_id: "schematic_component_simple_bug_0",
    source: null,
  },
  {
    type: "source_port",
    name: "RG",
    source_port_id: "source_port_10",
    source_component_id: "simple_bug_0",
    pin_number: 3,
    source: {
      type: "source_component",
      source_component_id: "simple_bug_0",
      name: "B1",
      ftype: "simple_bug",
    },
  },
  {
    type: "schematic_port",
    schematic_port_id: "schematic_port_10",
    source_port_id: "source_port_10",
    center: {
      x: 7.25,
      y: 3.5,
    },
    facing_direction: "left",
    schematic_component_id: "schematic_component_simple_bug_0",
    source: {
      type: "source_port",
      name: "RG",
      source_port_id: "source_port_10",
      source_component_id: "simple_bug_0",
      pin_number: 3,
    },
  },
  {
    type: "schematic_text",
    schematic_port_id: "schematic_port_10",
    schematic_text_id: "schematic_text_14",
    text: "3",
    anchor: "center",
    rotation: 0,
    position: {
      x: 7.373743686707646,
      y: 3.3762563132923544,
    },
    schematic_component_id: "schematic_component_simple_bug_0",
    source: null,
  },
  {
    type: "source_port",
    name: "D0",
    source_port_id: "source_port_11",
    source_component_id: "simple_bug_0",
    pin_number: 4,
    source: {
      type: "source_component",
      source_component_id: "simple_bug_0",
      name: "B1",
      ftype: "simple_bug",
    },
  },
  {
    type: "schematic_port",
    schematic_port_id: "schematic_port_11",
    source_port_id: "source_port_11",
    center: {
      x: 8.75,
      y: 2.5,
    },
    facing_direction: "right",
    schematic_component_id: "schematic_component_simple_bug_0",
    source: {
      type: "source_port",
      name: "D0",
      source_port_id: "source_port_11",
      source_component_id: "simple_bug_0",
      pin_number: 4,
    },
  },
  {
    type: "schematic_text",
    schematic_port_id: "schematic_port_11",
    schematic_text_id: "schematic_text_15",
    text: "4",
    anchor: "center",
    rotation: 0,
    position: {
      x: 8.626256313292354,
      y: 2.3762563132923544,
    },
    schematic_component_id: "schematic_component_simple_bug_0",
    source: null,
  },
  {
    type: "source_port",
    name: "D1",
    source_port_id: "source_port_12",
    source_component_id: "simple_bug_0",
    pin_number: 5,
    source: {
      type: "source_component",
      source_component_id: "simple_bug_0",
      name: "B1",
      ftype: "simple_bug",
    },
  },
  {
    type: "schematic_port",
    schematic_port_id: "schematic_port_12",
    source_port_id: "source_port_12",
    center: {
      x: 8.75,
      y: 3,
    },
    facing_direction: "right",
    schematic_component_id: "schematic_component_simple_bug_0",
    source: {
      type: "source_port",
      name: "D1",
      source_port_id: "source_port_12",
      source_component_id: "simple_bug_0",
      pin_number: 5,
    },
  },
  {
    type: "schematic_text",
    schematic_port_id: "schematic_port_12",
    schematic_text_id: "schematic_text_16",
    text: "5",
    anchor: "center",
    rotation: 0,
    position: {
      x: 8.626256313292354,
      y: 2.876256313292354,
    },
    schematic_component_id: "schematic_component_simple_bug_0",
    source: null,
  },
  {
    type: "source_port",
    name: "GND",
    source_port_id: "source_port_13",
    source_component_id: "simple_bug_0",
    pin_number: 6,
    source: {
      type: "source_component",
      source_component_id: "simple_bug_0",
      name: "B1",
      ftype: "simple_bug",
    },
  },
  {
    type: "schematic_port",
    schematic_port_id: "schematic_port_13",
    source_port_id: "source_port_13",
    center: {
      x: 8.75,
      y: 3.5,
    },
    facing_direction: "right",
    schematic_component_id: "schematic_component_simple_bug_0",
    source: {
      type: "source_port",
      name: "GND",
      source_port_id: "source_port_13",
      source_component_id: "simple_bug_0",
      pin_number: 6,
    },
  },
  {
    type: "schematic_text",
    schematic_port_id: "schematic_port_13",
    schematic_text_id: "schematic_text_17",
    text: "6",
    anchor: "center",
    rotation: 0,
    position: {
      x: 8.626256313292354,
      y: 3.3762563132923544,
    },
    schematic_component_id: "schematic_component_simple_bug_0",
    source: null,
  },
  {
    type: "schematic_text",
    schematic_text_id: "schematic_text_6",
    schematic_component_id: "schematic_component_simple_bug_0",
    text: "PWR",
    anchor: "left",
    rotation: 0,
    position: {
      x: 7.65,
      y: 2.5,
    },
    source: null,
  },
  {
    type: "schematic_text",
    schematic_text_id: "schematic_text_7",
    schematic_component_id: "schematic_component_simple_bug_0",
    text: "NC",
    anchor: "left",
    rotation: 0,
    position: {
      x: 7.65,
      y: 3,
    },
    source: null,
  },
  {
    type: "schematic_text",
    schematic_text_id: "schematic_text_8",
    schematic_component_id: "schematic_component_simple_bug_0",
    text: "RG",
    anchor: "left",
    rotation: 0,
    position: {
      x: 7.65,
      y: 3.5,
    },
    source: null,
  },
  {
    type: "schematic_text",
    schematic_text_id: "schematic_text_9",
    schematic_component_id: "schematic_component_simple_bug_0",
    text: "D0",
    anchor: "right",
    rotation: 0,
    position: {
      x: 8.35,
      y: 2.5,
    },
    source: null,
  },
  {
    type: "schematic_text",
    schematic_text_id: "schematic_text_10",
    schematic_component_id: "schematic_component_simple_bug_0",
    text: "D1",
    anchor: "right",
    rotation: 0,
    position: {
      x: 8.35,
      y: 3,
    },
    source: null,
  },
  {
    type: "schematic_text",
    schematic_text_id: "schematic_text_11",
    schematic_component_id: "schematic_component_simple_bug_0",
    text: "GND",
    anchor: "right",
    rotation: 0,
    position: {
      x: 8.35,
      y: 3.5,
    },
    source: null,
  },
  {
    type: "source_component",
    source_component_id: "simple_ground_0",
    name: "GND",
    ftype: "simple_ground",
    source: {
      type: "source_component",
      source_component_id: "simple_ground_0",
      name: "GND",
      ftype: "simple_ground",
    },
  },
  {
    type: "schematic_component",
    source_component_id: "simple_ground_0",
    schematic_component_id: "schematic_component_simple_ground_0",
    rotation: 0,
    size: {
      width: 0.5,
      height: 0.4166666666666667,
    },
    center: {
      x: 11,
      y: 3,
    },
    source: {
      type: "source_component",
      source_component_id: "simple_ground_0",
      name: "GND",
      ftype: "simple_ground",
    },
  },
  {
    type: "source_port",
    name: "gnd",
    source_port_id: "source_port_14",
    source_component_id: "simple_ground_0",
    source: {
      type: "source_component",
      source_component_id: "simple_ground_0",
      name: "GND",
      ftype: "simple_ground",
    },
  },
  {
    type: "schematic_port",
    schematic_port_id: "schematic_port_14",
    source_port_id: "source_port_14",
    center: {
      x: 11,
      y: 2.8,
    },
    facing_direction: "up",
    schematic_component_id: "schematic_component_simple_ground_0",
    source: {
      type: "source_port",
      name: "gnd",
      source_port_id: "source_port_14",
      source_component_id: "simple_ground_0",
    },
  },
  {
    type: "source_component",
    source_component_id: "simple_diode_0",
    name: "D1",
    ftype: "simple_diode",
    source: {
      type: "source_component",
      source_component_id: "simple_diode_0",
      name: "D1",
      ftype: "simple_diode",
    },
  },
  {
    type: "schematic_component",
    schematic_component_id: "schematic_simple_diode_component_0",
    source_component_id: "simple_diode_0",
    center: {
      x: 6,
      y: 3.5,
    },
    rotation: 3.141592653589793,
    size: {
      width: 1,
      height: 0.45899999999999963,
    },
    source: {
      type: "source_component",
      source_component_id: "simple_diode_0",
      name: "D1",
      ftype: "simple_diode",
    },
  },
  {
    type: "source_port",
    name: "left",
    source_port_id: "source_port_15",
    source_component_id: "simple_diode_0",
    source: {
      type: "source_component",
      source_component_id: "simple_diode_0",
      name: "D1",
      ftype: "simple_diode",
    },
  },
  {
    type: "schematic_port",
    schematic_port_id: "schematic_port_15",
    source_port_id: "source_port_15",
    center: {
      x: 6.5,
      y: 3.5,
    },
    schematic_component_id: "schematic_simple_diode_component_0",
    source: {
      type: "source_port",
      name: "left",
      source_port_id: "source_port_15",
      source_component_id: "simple_diode_0",
    },
  },
  {
    type: "source_port",
    name: "right",
    source_port_id: "source_port_16",
    source_component_id: "simple_diode_0",
    source: {
      type: "source_component",
      source_component_id: "simple_diode_0",
      name: "D1",
      ftype: "simple_diode",
    },
  },
  {
    type: "schematic_port",
    schematic_port_id: "schematic_port_16",
    source_port_id: "source_port_16",
    center: {
      x: 5.5,
      y: 3.5,
    },
    schematic_component_id: "schematic_simple_diode_component_0",
    source: {
      type: "source_port",
      name: "right",
      source_port_id: "source_port_16",
      source_component_id: "simple_diode_0",
    },
  },
  {
    drawing_type: "line",
    type: "schematic_line",
    x1: 6.5,
    y1: 3.5,
    x2: 6.1557,
    y2: 3.5,
    schematic_component_id: "schematic_simple_diode_component_0",
    source: null,
  },
  {
    drawing_type: "line",
    type: "schematic_line",
    x1: 5.6967,
    y1: 3.5,
    x2: 5.5,
    y2: 3.5,
    schematic_component_id: "schematic_simple_diode_component_0",
    source: null,
  },
  {
    drawing_type: "line",
    type: "schematic_line",
    x1: 5.6967,
    y1: 3.5,
    x2: 6.1557,
    y2: 3.2705,
    schematic_component_id: "schematic_simple_diode_component_0",
    source: null,
  },
  {
    drawing_type: "line",
    type: "schematic_line",
    x1: 6.1557,
    y1: 3.2705,
    x2: 6.1557,
    y2: 3.7295,
    schematic_component_id: "schematic_simple_diode_component_0",
    source: null,
  },
  {
    drawing_type: "line",
    type: "schematic_line",
    x1: 6.1557,
    y1: 3.7295,
    x2: 5.6967,
    y2: 3.5,
    schematic_component_id: "schematic_simple_diode_component_0",
    source: null,
  },
  {
    drawing_type: "line",
    type: "schematic_line",
    x1: 5.6967,
    y1: 3.7295,
    x2: 5.6967,
    y2: 3.2705,
    schematic_component_id: "schematic_simple_diode_component_0",
    source: null,
  },
  {
    anchor: "center",
    type: "schematic_text",
    position: {
      x: 6,
      y: 3.75,
    },
    text: "D1",
    schematic_component_id: "schematic_simple_diode_component_0",
    source: null,
  },
  {
    type: "source_trace",
    source_trace_id: "source_trace_0",
    connected_source_port_ids: [
      "source_port_1",
      "source_port_2",
      "source_port_4",
    ],
    source: null,
  },
  {
    type: "schematic_trace",
    source_trace_id: "source_trace_0",
    schematic_trace_id: "schematic_trace_0",
    edges: [
      {
        from: {
          x: 2.6,
          y: 1,
        },
        to: {
          x: 3.1,
          y: 1,
        },
      },
      {
        from: {
          x: 3.1,
          y: 1,
        },
        to: {
          x: 3.1,
          y: 1.5,
        },
      },
      {
        from: {
          x: 3.1,
          y: 1.5,
        },
        to: {
          x: 4,
          y: 1.5,
        },
      },
      {
        from: {
          x: 4,
          y: 1.5,
        },
        to: {
          x: 4,
          y: 1.5,
        },
      },
      {
        from: {
          x: 4,
          y: 1.5,
        },
        to: {
          x: 4,
          y: 0.5,
        },
      },
      {
        from: {
          x: 4,
          y: 0.5,
        },
        to: {
          x: 6,
          y: 0.5,
        },
      },
    ],
    source: null,
  },
  {
    type: "source_trace",
    source_trace_id: "source_trace_1",
    connected_source_port_ids: ["source_port_6", "source_port_0"],
    source: null,
  },
  {
    type: "schematic_trace",
    source_trace_id: "source_trace_1",
    schematic_trace_id: "schematic_trace_1",
    edges: [
      {
        from: {
          x: 1,
          y: 1.4000000000000001,
        },
        to: {
          x: 1,
          y: 1,
        },
      },
      {
        from: {
          x: 1,
          y: 1,
        },
        to: {
          x: 1.4000000000000001,
          y: 1,
        },
      },
    ],
    source: null,
  },
  {
    type: "source_trace",
    source_trace_id: "source_trace_2",
    connected_source_port_ids: [
      "source_port_7",
      "source_port_3",
      "source_port_5",
    ],
    source: null,
  },
  {
    type: "schematic_trace",
    source_trace_id: "source_trace_2",
    schematic_trace_id: "schematic_trace_2",
    edges: [
      {
        from: {
          x: 1,
          y: 2.6,
        },
        to: {
          x: 1,
          y: 2.5,
        },
      },
      {
        from: {
          x: 1,
          y: 2.5,
        },
        to: {
          x: 4,
          y: 2.5,
        },
      },
      {
        from: {
          x: 4,
          y: 2.5,
        },
        to: {
          x: 4,
          y: 2.5,
        },
      },
      {
        from: {
          x: 4,
          y: 2.5,
        },
        to: {
          x: 4,
          y: 2.4000000000000004,
        },
      },
      {
        from: {
          x: 4,
          y: 2.4000000000000004,
        },
        to: {
          x: 5.7,
          y: 2.4000000000000004,
        },
      },
      {
        from: {
          x: 5.7,
          y: 2.4000000000000004,
        },
        to: {
          x: 5.7,
          y: 1.5,
        },
      },
      {
        from: {
          x: 5.7,
          y: 1.5,
        },
        to: {
          x: 6,
          y: 1.5,
        },
      },
    ],
    source: null,
  },
  {
    type: "source_trace",
    source_trace_id: "source_trace_3",
    connected_source_port_ids: ["source_port_8", "source_port_4"],
    source: null,
  },
  {
    type: "schematic_trace",
    source_trace_id: "source_trace_3",
    schematic_trace_id: "schematic_trace_3",
    edges: [
      {
        from: {
          x: 6,
          y: 0.5,
        },
        to: {
          x: 7.300000000000001,
          y: 0.5,
        },
      },
      {
        from: {
          x: 7.300000000000001,
          y: 0.5,
        },
        to: {
          x: 7.300000000000001,
          y: 2.5,
        },
      },
    ],
    source: null,
  },
  {
    type: "source_trace",
    source_trace_id: "source_trace_4",
    connected_source_port_ids: ["source_port_13", "source_port_14"],
    source: null,
  },
  {
    type: "schematic_trace",
    source_trace_id: "source_trace_4",
    schematic_trace_id: "schematic_trace_4",
    edges: [
      {
        from: {
          x: 8.700000000000001,
          y: 3.5,
        },
        to: {
          x: 10.100000000000001,
          y: 3.5,
        },
      },
      {
        from: {
          x: 10.100000000000001,
          y: 3.5,
        },
        to: {
          x: 10.100000000000001,
          y: 2.7,
        },
      },
      {
        from: {
          x: 10.100000000000001,
          y: 2.7,
        },
        to: {
          x: 11,
          y: 2.7,
        },
      },
    ],
    source: null,
  },
  {
    type: "source_trace",
    source_trace_id: "source_trace_5",
    connected_source_port_ids: ["source_port_15", "source_port_10"],
    source: null,
  },
  {
    type: "schematic_trace",
    source_trace_id: "source_trace_5",
    schematic_trace_id: "schematic_trace_5",
    edges: [
      {
        from: {
          x: 6.6000000000000005,
          y: 3.5,
        },
        to: {
          x: 7.200000000000001,
          y: 3.5,
        },
      },
    ],
    source: null,
  },
  {
    type: "source_trace",
    source_trace_id: "source_trace_6",
    connected_source_port_ids: ["source_port_16", "source_port_3"],
    source: null,
  },
  {
    type: "schematic_trace",
    source_trace_id: "source_trace_6",
    schematic_trace_id: "schematic_trace_6",
    edges: [
      {
        from: {
          x: 4,
          y: 2.5,
        },
        to: {
          x: 5.4,
          y: 2.5,
        },
      },
      {
        from: {
          x: 5.4,
          y: 2.5,
        },
        to: {
          x: 5.4,
          y: 3.5,
        },
      },
    ],
    source: null,
  },
]

export const exampleSoupPcb = [
  {
    type: "source_component",
    source_component_id: "simple_resistor_0",
    name: "R1",
    ftype: "simple_resistor",
    resistance: "10 ohm",
    source: {
      type: "source_component",
      source_component_id: "simple_resistor_0",
      name: "R1",
      ftype: "simple_resistor",
      resistance: "10 ohm",
    },
  },
  {
    type: "source_port",
    name: "left",
    source_port_id: "source_port_0",
    source_component_id: "simple_resistor_0",
    source: {
      type: "source_component",
      source_component_id: "simple_resistor_0",
      name: "R1",
      ftype: "simple_resistor",
      resistance: "10 ohm",
    },
  },
  {
    type: "pcb_port",
    pcb_port_id: "pcb_port_0",
    source_port_id: "source_port_0",
    x: -0.5,
    y: 0,
    source: {
      type: "source_port",
      name: "left",
      source_port_id: "source_port_0",
      source_component_id: "simple_resistor_0",
    },
  },
  {
    type: "source_port",
    name: "right",
    source_port_id: "source_port_1",
    source_component_id: "simple_resistor_0",
    source: {
      type: "source_component",
      source_component_id: "simple_resistor_0",
      name: "R1",
      ftype: "simple_resistor",
      resistance: "10 ohm",
    },
  },
  {
    type: "pcb_port",
    pcb_port_id: "pcb_port_1",
    source_port_id: "source_port_1",
    x: 0.5,
    y: 0,
    source: {
      type: "source_port",
      name: "right",
      source_port_id: "source_port_1",
      source_component_id: "simple_resistor_0",
    },
  },
  {
    type: "pcb_component",
    source_component_id: "simple_resistor_0",
    pcb_component_id: "pcb_component_simple_resistor_0",
    source: {
      type: "source_component",
      source_component_id: "simple_resistor_0",
      name: "R1",
      ftype: "simple_resistor",
      resistance: "10 ohm",
    },
  },
  {
    type: "pcb_smtpad",
    shape: "rect",
    x: -0.5,
    y: 0,
    width: 0.6,
    height: 0.6,
    layer: {
      name: "top",
    },
    pcb_component_id: "pcb_component_simple_resistor_0",
    port_hints: ["left", "1"],
    pcb_port_id: "pcb_port_0",
    source: null,
  },
  {
    type: "pcb_smtpad",
    shape: "rect",
    x: 0.5,
    y: 0,
    width: 0.6,
    height: 0.6,
    layer: {
      name: "top",
    },
    pcb_component_id: "pcb_component_simple_resistor_0",
    port_hints: ["right", "2"],
    pcb_port_id: "pcb_port_1",
    source: null,
  },
  {
    type: "source_component",
    source_component_id: "simple_capacitor_0",
    name: "C1",
    ftype: "simple_capacitor",
    capacitance: "10 uF",
    source: {
      type: "source_component",
      source_component_id: "simple_capacitor_0",
      name: "C1",
      ftype: "simple_capacitor",
      capacitance: "10 uF",
    },
  },
  {
    type: "source_port",
    name: "left",
    source_port_id: "source_port_2",
    source_component_id: "simple_capacitor_0",
    source: {
      type: "source_component",
      source_component_id: "simple_capacitor_0",
      name: "C1",
      ftype: "simple_capacitor",
      capacitance: "10 uF",
    },
  },
  {
    type: "pcb_port",
    pcb_port_id: "pcb_port_2",
    source_port_id: "source_port_2",
    x: 3.5,
    y: 0,
    source: {
      type: "source_port",
      name: "left",
      source_port_id: "source_port_2",
      source_component_id: "simple_capacitor_0",
    },
  },
  {
    type: "source_port",
    name: "right",
    source_port_id: "source_port_3",
    source_component_id: "simple_capacitor_0",
    source: {
      type: "source_component",
      source_component_id: "simple_capacitor_0",
      name: "C1",
      ftype: "simple_capacitor",
      capacitance: "10 uF",
    },
  },
  {
    type: "pcb_port",
    pcb_port_id: "pcb_port_3",
    source_port_id: "source_port_3",
    x: 4.5,
    y: 0,
    source: {
      type: "source_port",
      name: "right",
      source_port_id: "source_port_3",
      source_component_id: "simple_capacitor_0",
    },
  },
  {
    type: "pcb_component",
    source_component_id: "simple_capacitor_0",
    pcb_component_id: "pcb_component_simple_capacitor_0",
    source: {
      type: "source_component",
      source_component_id: "simple_capacitor_0",
      name: "C1",
      ftype: "simple_capacitor",
      capacitance: "10 uF",
    },
  },
  {
    type: "pcb_smtpad",
    shape: "rect",
    x: 3.5,
    y: 0,
    width: 0.6,
    height: 0.6,
    layer: {
      name: "top",
    },
    pcb_component_id: "pcb_component_simple_capacitor_0",
    port_hints: ["left", "1"],
    pcb_port_id: "pcb_port_2",
    source: null,
  },
  {
    type: "pcb_smtpad",
    shape: "rect",
    x: 4.5,
    y: 0,
    width: 0.6,
    height: 0.6,
    layer: {
      name: "top",
    },
    pcb_component_id: "pcb_component_simple_capacitor_0",
    port_hints: ["right", "2"],
    pcb_port_id: "pcb_port_3",
    source: null,
  },
  {
    type: "source_component",
    source_component_id: "simple_resistor_1",
    name: "R2",
    ftype: "simple_resistor",
    resistance: "10 ohm",
    source: {
      type: "source_component",
      source_component_id: "simple_resistor_1",
      name: "R2",
      ftype: "simple_resistor",
      resistance: "10 ohm",
    },
  },
  {
    type: "source_port",
    name: "left",
    source_port_id: "source_port_4",
    source_component_id: "simple_resistor_1",
    source: {
      type: "source_component",
      source_component_id: "simple_resistor_1",
      name: "R2",
      ftype: "simple_resistor",
      resistance: "10 ohm",
    },
  },
  {
    type: "pcb_port",
    pcb_port_id: "pcb_port_4",
    source_port_id: "source_port_4",
    source: {
      type: "source_port",
      name: "left",
      source_port_id: "source_port_4",
      source_component_id: "simple_resistor_1",
    },
  },
  {
    type: "source_port",
    name: "right",
    source_port_id: "source_port_5",
    source_component_id: "simple_resistor_1",
    source: {
      type: "source_component",
      source_component_id: "simple_resistor_1",
      name: "R2",
      ftype: "simple_resistor",
      resistance: "10 ohm",
    },
  },
  {
    type: "pcb_port",
    pcb_port_id: "pcb_port_5",
    source_port_id: "source_port_5",
    source: {
      type: "source_port",
      name: "right",
      source_port_id: "source_port_5",
      source_component_id: "simple_resistor_1",
    },
  },
  {
    type: "pcb_component",
    source_component_id: "simple_resistor_1",
    pcb_component_id: "pcb_component_simple_resistor_1",
    source: {
      type: "source_component",
      source_component_id: "simple_resistor_1",
      name: "R2",
      ftype: "simple_resistor",
      resistance: "10 ohm",
    },
  },
  {
    type: "source_component",
    source_component_id: "simple_power_source_0",
    name: "main_power",
    ftype: "simple_power_source",
    voltage: "5V",
    source: {
      type: "source_component",
      source_component_id: "simple_power_source_0",
      name: "main_power",
      ftype: "simple_power_source",
      voltage: "5V",
    },
  },
  {
    type: "source_port",
    name: "positive",
    source_port_id: "source_port_6",
    source_component_id: "simple_power_source_0",
    source: {
      type: "source_component",
      source_component_id: "simple_power_source_0",
      name: "main_power",
      ftype: "simple_power_source",
      voltage: "5V",
    },
  },
  {
    type: "pcb_port",
    pcb_port_id: "pcb_port_6",
    source_port_id: "source_port_6",
    source: {
      type: "source_port",
      name: "positive",
      source_port_id: "source_port_6",
      source_component_id: "simple_power_source_0",
    },
  },
  {
    type: "source_port",
    name: "negative",
    source_port_id: "source_port_7",
    source_component_id: "simple_power_source_0",
    source: {
      type: "source_component",
      source_component_id: "simple_power_source_0",
      name: "main_power",
      ftype: "simple_power_source",
      voltage: "5V",
    },
  },
  {
    type: "pcb_port",
    pcb_port_id: "pcb_port_7",
    source_port_id: "source_port_7",
    source: {
      type: "source_port",
      name: "negative",
      source_port_id: "source_port_7",
      source_component_id: "simple_power_source_0",
    },
  },
  {
    type: "pcb_component",
    source_component_id: "simple_power_source_0",
    pcb_component_id: "pcb_component_simple_power_source_0",
    source: {
      type: "source_component",
      source_component_id: "simple_power_source_0",
      name: "main_power",
      ftype: "simple_power_source",
      voltage: "5V",
    },
  },
  {
    type: "source_component",
    source_component_id: "simple_bug_0",
    name: "B1",
    ftype: "simple_bug",
    source: {
      type: "source_component",
      source_component_id: "simple_bug_0",
      name: "B1",
      ftype: "simple_bug",
    },
  },
  {
    type: "source_port",
    name: "PWR",
    source_port_id: "source_port_8",
    source_component_id: "simple_bug_0",
    pin_number: 1,
    source: {
      type: "source_component",
      source_component_id: "simple_bug_0",
      name: "B1",
      ftype: "simple_bug",
    },
  },
  {
    type: "pcb_port",
    pcb_port_id: "pcb_port_8",
    source_port_id: "source_port_8",
    source: {
      type: "source_port",
      name: "PWR",
      source_port_id: "source_port_8",
      source_component_id: "simple_bug_0",
      pin_number: 1,
    },
  },
  {
    type: "source_port",
    name: "NC",
    source_port_id: "source_port_9",
    source_component_id: "simple_bug_0",
    pin_number: 2,
    source: {
      type: "source_component",
      source_component_id: "simple_bug_0",
      name: "B1",
      ftype: "simple_bug",
    },
  },
  {
    type: "pcb_port",
    pcb_port_id: "pcb_port_9",
    source_port_id: "source_port_9",
    source: {
      type: "source_port",
      name: "NC",
      source_port_id: "source_port_9",
      source_component_id: "simple_bug_0",
      pin_number: 2,
    },
  },
  {
    type: "source_port",
    name: "RG",
    source_port_id: "source_port_10",
    source_component_id: "simple_bug_0",
    pin_number: 3,
    source: {
      type: "source_component",
      source_component_id: "simple_bug_0",
      name: "B1",
      ftype: "simple_bug",
    },
  },
  {
    type: "pcb_port",
    pcb_port_id: "pcb_port_10",
    source_port_id: "source_port_10",
    source: {
      type: "source_port",
      name: "RG",
      source_port_id: "source_port_10",
      source_component_id: "simple_bug_0",
      pin_number: 3,
    },
  },
  {
    type: "source_port",
    name: "D0",
    source_port_id: "source_port_11",
    source_component_id: "simple_bug_0",
    pin_number: 4,
    source: {
      type: "source_component",
      source_component_id: "simple_bug_0",
      name: "B1",
      ftype: "simple_bug",
    },
  },
  {
    type: "pcb_port",
    pcb_port_id: "pcb_port_11",
    source_port_id: "source_port_11",
    source: {
      type: "source_port",
      name: "D0",
      source_port_id: "source_port_11",
      source_component_id: "simple_bug_0",
      pin_number: 4,
    },
  },
  {
    type: "source_port",
    name: "D1",
    source_port_id: "source_port_12",
    source_component_id: "simple_bug_0",
    pin_number: 5,
    source: {
      type: "source_component",
      source_component_id: "simple_bug_0",
      name: "B1",
      ftype: "simple_bug",
    },
  },
  {
    type: "pcb_port",
    pcb_port_id: "pcb_port_12",
    source_port_id: "source_port_12",
    source: {
      type: "source_port",
      name: "D1",
      source_port_id: "source_port_12",
      source_component_id: "simple_bug_0",
      pin_number: 5,
    },
  },
  {
    type: "source_port",
    name: "GND",
    source_port_id: "source_port_13",
    source_component_id: "simple_bug_0",
    pin_number: 6,
    source: {
      type: "source_component",
      source_component_id: "simple_bug_0",
      name: "B1",
      ftype: "simple_bug",
    },
  },
  {
    type: "pcb_port",
    pcb_port_id: "pcb_port_13",
    source_port_id: "source_port_13",
    source: {
      type: "source_port",
      name: "GND",
      source_port_id: "source_port_13",
      source_component_id: "simple_bug_0",
      pin_number: 6,
    },
  },
  {
    type: "pcb_component",
    source_component_id: "simple_bug_0",
    pcb_component_id: "pcb_component_simple_bug_0",
    source: {
      type: "source_component",
      source_component_id: "simple_bug_0",
      name: "B1",
      ftype: "simple_bug",
    },
  },
  {
    type: "source_component",
    source_component_id: "simple_ground_0",
    name: "GND",
    ftype: "simple_ground",
    source: {
      type: "source_component",
      source_component_id: "simple_ground_0",
      name: "GND",
      ftype: "simple_ground",
    },
  },
  {
    type: "source_port",
    name: "gnd",
    source_port_id: "source_port_14",
    source_component_id: "simple_ground_0",
    source: {
      type: "source_component",
      source_component_id: "simple_ground_0",
      name: "GND",
      ftype: "simple_ground",
    },
  },
  {
    type: "pcb_port",
    pcb_port_id: "pcb_port_14",
    source_port_id: "source_port_14",
    source: {
      type: "source_port",
      name: "gnd",
      source_port_id: "source_port_14",
      source_component_id: "simple_ground_0",
    },
  },
  {
    type: "pcb_component",
    source_component_id: "simple_ground_0",
    pcb_component_id: "pcb_component_simple_ground_0",
    source: {
      type: "source_component",
      source_component_id: "simple_ground_0",
      name: "GND",
      ftype: "simple_ground",
    },
  },
  {
    type: "source_component",
    source_component_id: "simple_diode_0",
    name: "D1",
    ftype: "simple_diode",
    source: {
      type: "source_component",
      source_component_id: "simple_diode_0",
      name: "D1",
      ftype: "simple_diode",
    },
  },
  {
    type: "pcb_component",
    source_component_id: "simple_diode_0",
    pcb_component_id: "pcb_simple_diode_component_0",
    source: {
      type: "source_component",
      source_component_id: "simple_diode_0",
      name: "D1",
      ftype: "simple_diode",
    },
  },
  {
    type: "source_port",
    name: "left",
    source_port_id: "source_port_15",
    source_component_id: "simple_diode_0",
    source: {
      type: "source_component",
      source_component_id: "simple_diode_0",
      name: "D1",
      ftype: "simple_diode",
    },
  },
  {
    type: "pcb_port",
    pcb_port_id: "pcb_port_15",
    source_port_id: "source_port_15",
    source: {
      type: "source_port",
      name: "left",
      source_port_id: "source_port_15",
      source_component_id: "simple_diode_0",
    },
  },
  {
    type: "source_port",
    name: "right",
    source_port_id: "source_port_16",
    source_component_id: "simple_diode_0",
    source: {
      type: "source_component",
      source_component_id: "simple_diode_0",
      name: "D1",
      ftype: "simple_diode",
    },
  },
  {
    type: "pcb_port",
    pcb_port_id: "pcb_port_16",
    source_port_id: "source_port_16",
    source: {
      type: "source_port",
      name: "right",
      source_port_id: "source_port_16",
      source_component_id: "simple_diode_0",
    },
  },
  {
    type: "source_trace",
    source_trace_id: "source_trace_0",
    connected_source_port_ids: [
      "source_port_1",
      "source_port_2",
      "source_port_4",
    ],
    source: null,
  },
  {
    type: "pcb_trace",
    pcb_trace_id: "pcb_trace_0",
    source_trace_id: "source_trace_0",
    route: [],
    source: null,
  },
  {
    type: "source_trace",
    source_trace_id: "source_trace_1",
    connected_source_port_ids: ["source_port_6", "source_port_0"],
    source: null,
  },
  {
    type: "pcb_trace",
    pcb_trace_id: "pcb_trace_1",
    source_trace_id: "source_trace_1",
    route: [],
    source: null,
  },
  {
    pcb_error_id: "pcb_error_0",
    type: "pcb_error",
    error_type: "pcb_trace_error",
    message:
      "Error while pcb-trace-route solving: TypeError: Cannot read properties of undefined (reading 'targetDistance')",
    pcb_trace_id: "pcb_trace_1",
    source_trace_id: "source_trace_1",
    pcb_component_ids: [],
    pcb_port_ids: ["pcb_port_6", "pcb_port_0"],
    source: null,
  },
  {
    type: "source_trace",
    source_trace_id: "source_trace_2",
    connected_source_port_ids: [
      "source_port_7",
      "source_port_3",
      "source_port_5",
    ],
    source: null,
  },
  {
    type: "pcb_trace",
    pcb_trace_id: "pcb_trace_2",
    source_trace_id: "source_trace_2",
    route: [],
    source: null,
  },
  {
    pcb_error_id: "pcb_error_1",
    type: "pcb_error",
    error_type: "pcb_trace_error",
    message:
      "Error while pcb-trace-route solving: TypeError: Cannot read properties of undefined (reading 'targetDistance')",
    pcb_trace_id: "pcb_trace_2",
    source_trace_id: "source_trace_2",
    pcb_component_ids: [],
    pcb_port_ids: ["pcb_port_7", "pcb_port_3", "pcb_port_5"],
    source: null,
  },
  {
    type: "source_trace",
    source_trace_id: "source_trace_3",
    connected_source_port_ids: ["source_port_8", "source_port_4"],
    source: null,
  },
  {
    type: "pcb_trace",
    pcb_trace_id: "pcb_trace_3",
    source_trace_id: "source_trace_3",
    route: [],
    source: null,
  },
  {
    pcb_error_id: "pcb_error_2",
    type: "pcb_error",
    error_type: "pcb_trace_error",
    message:
      "Error while pcb-trace-route solving: TypeError: Cannot read properties of undefined (reading 'targetDistance')",
    pcb_trace_id: "pcb_trace_3",
    source_trace_id: "source_trace_3",
    pcb_component_ids: [],
    pcb_port_ids: ["pcb_port_8", "pcb_port_4"],
    source: null,
  },
  {
    type: "source_trace",
    source_trace_id: "source_trace_4",
    connected_source_port_ids: ["source_port_13", "source_port_14"],
    source: null,
  },
  {
    type: "pcb_trace",
    pcb_trace_id: "pcb_trace_4",
    source_trace_id: "source_trace_4",
    route: [],
    source: null,
  },
  {
    pcb_error_id: "pcb_error_3",
    type: "pcb_error",
    error_type: "pcb_trace_error",
    message:
      "Error while pcb-trace-route solving: TypeError: Cannot read properties of undefined (reading 'targetDistance')",
    pcb_trace_id: "pcb_trace_4",
    source_trace_id: "source_trace_4",
    pcb_component_ids: [],
    pcb_port_ids: ["pcb_port_13", "pcb_port_14"],
    source: null,
  },
  {
    type: "source_trace",
    source_trace_id: "source_trace_5",
    connected_source_port_ids: ["source_port_15", "source_port_10"],
    source: null,
  },
  {
    type: "pcb_trace",
    pcb_trace_id: "pcb_trace_5",
    source_trace_id: "source_trace_5",
    route: [],
    source: null,
  },
  {
    pcb_error_id: "pcb_error_4",
    type: "pcb_error",
    error_type: "pcb_trace_error",
    message:
      "Error while pcb-trace-route solving: TypeError: Cannot read properties of undefined (reading 'targetDistance')",
    pcb_trace_id: "pcb_trace_5",
    source_trace_id: "source_trace_5",
    pcb_component_ids: [],
    pcb_port_ids: ["pcb_port_15", "pcb_port_10"],
    source: null,
  },
  {
    type: "source_trace",
    source_trace_id: "source_trace_6",
    connected_source_port_ids: ["source_port_16", "source_port_3"],
    source: null,
  },
  {
    type: "pcb_trace",
    pcb_trace_id: "pcb_trace_6",
    source_trace_id: "source_trace_6",
    route: [],
    source: null,
  },
  {
    pcb_error_id: "pcb_error_5",
    type: "pcb_error",
    error_type: "pcb_trace_error",
    message:
      "Error while pcb-trace-route solving: TypeError: Cannot read properties of undefined (reading 'targetDistance')",
    pcb_trace_id: "pcb_trace_6",
    source_trace_id: "source_trace_6",
    pcb_component_ids: [],
    pcb_port_ids: ["pcb_port_16", "pcb_port_3"],
    source: null,
  },
]
